export const COPY = {
  appName: "SocialNews",
  appDescription: "Content management and news following in social media format.",

  nav: {
    home: "Home",
    search: "Search",
    explore: "Explore",
    compose: "Create",
    notifications: "Notifications",
    profile: "Profile",
    settings: "Settings",
    moderation: "Moderation",
    admin: "Admin Dashboard",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    more: "More",
  },

  actions: {
    post: "Post",
    publishPost: "Publish Post",
    saveProfile: "Save Profile",
    editProfile: "Edit Profile",
    cancel: "Cancel",
    confirm: "Confirm",
    delete: "Delete",
    deletePost: "Delete Post",
    hideContent: "Hide Content",
    restoreContent: "Restore Content",
    removeContent: "Remove Content",
    escalateToAdmin: "Escalate to Admin",
    submitReport: "Submit Report",
    dismissReport: "Dismiss Report",
    actionReport: "Action Report",
    review: "Review",
    follow: "Follow",
    following: "Following",
    unfollow: "Unfollow",
    like: "Like",
    unlike: "Unlike",
    share: "Share",
    comment: "Comment",
    retry: "Retry",
    loadMore: "Load More",
    exportCsv: "Export CSV",
    refresh: "Refresh",
  },

  feed: {
    title: "News Feed",
    latest: "Latest",
    following: "Following",
    emptyTitle: "No posts yet",
    emptyDescription: "Follow other accounts or create your first post to start the conversation.",
    emptyExploreTitle: "No posts to explore",
    emptyExploreDescription: "Check back later for popular news and stories.",
  },

  post: {
    addCommentPlaceholder: "Add a comment…",
    titlePlaceholder: "Add a headline (optional)…",
    bodyPlaceholder: "What is happening in the news today?…",
    tagsPlaceholder: "e.g. technology, politics, science…",
    likes: (count) => (count === 1 ? "1 like" : `${count} likes`),
    comments: (count) => (count === 1 ? "1 comment" : `${count} comments`),
    shares: (count) => (count === 1 ? "1 share" : `${count} shares`),
    viewAllComments: (count) => `View all ${count} comments`,
    more: "more",
  },

  search: {
    placeholder: "Search accounts, tags, or stories…",
    accounts: "Accounts",
    tags: "Tags",
    posts: "Posts",
    emptyTitle: "No results found",
    emptyDescription: "Try searching with different keywords or check your spelling.",
  },

  notifications: {
    title: "Notifications",
    emptyTitle: "No notifications yet",
    emptyDescription: "When people like your posts, comment, or follow you, updates will appear here.",
    today: "Today",
    thisWeek: "This Week",
    earlier: "Earlier",
  },

  moderation: {
    title: "Moderation Queue",
    emptyTitle: "Queue is clear",
    emptyDescription: "There are no pending reports requiring moderator review at this time.",
    statusPending: "Pending",
    statusInReview: "In Review",
    statusEscalated: "Escalated",
    statusActioned: "Resolved (Actioned)",
    statusDismissed: "Resolved (Dismissed)",
  },

  admin: {
    title: "Admin Dashboard",
    userManagement: "User Management",
    auditLog: "Audit Log",
    systemStats: "System Statistics",
  },

  auth: {
    signInTitle: "Sign In to SocialNews",
    signUpTitle: "Create Your Account",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    usernameLabel: "Username",
    displayNameLabel: "Display Name",
    emailPlaceholder: "e.g. reader@example.com…",
    usernamePlaceholder: "e.g. tech_reporter…",
    displayNamePlaceholder: "e.g. Jane Doe…",
    passwordPlaceholder: "Enter your password…",
    dontHaveAccount: "Do not have an account? Sign up",
    alreadyHaveAccount: "Already have an account? Sign in",
  },

  states: {
    loading: "Loading…",
    saving: "Saving…",
    submitting: "Submitting…",
    errorGeneric: "An unexpected error occurred. Please check your connection and try again.",
  },
};
